openapi: 3.0.0
info:
  title: Readiness API
  version: 1.0.0
paths:
  /readiness/{storyId}/evaluate:
    post:
      summary: Evaluate the readiness of a story
      security:
        - bearerAuth: []
      parameters:
        - name: storyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Readiness evaluated
          content:
            application/json:
              schema:
                type: object
                properties:
                  score:
                    type: integer
                  missingItems:
                    type: array
                    items:
                      type: string
  /criteria/{storyId}/generate:
    post:
      summary: Generate BDD criteria for a story
      security:
        - bearerAuth: []
      parameters:
        - name: storyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Criteria generated
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    storyId:
                      type: string
                      format: uuid
                    ac_id:
                      type: string
                      description: Unique identifier for this acceptance criterion
                    given:
                      type: string
                    when:
                      type: string
                    then:
                      type: string
  /criteria/{storyId}:
    get:
      summary: Get the BDD criteria for a story
      parameters:
        - name: storyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Criteria list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    storyId:
                      type: string
                      format: uuid
                    ac_id:
                      type: string
                      description: Unique identifier for this acceptance criterion
                    given:
                      type: string
                    when:
                      type: string
                    then:
                      type: string
    post:
      summary: Add BDD criteria for a story
      security:
        - bearerAuth: []
      parameters:
        - name: storyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                criteria:
                  type: array
                  items:
                    type: object
                    properties:
                      ac_id:
                        type: string
                        description: Unique identifier for this acceptance criterion
                      given:
                        type: string
                      when:
                        type: string
                      then:
                        type: string
      responses:
        '201':
          description: Criteria added
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    storyId:
                      type: string
                      format: uuid
                    ac_id:
                      type: string
                      description: Unique identifier for this acceptance criterion
                    given:
                      type: string
                    when:
                      type: string
                    then:
                      type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
