name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.79

    - name: Install cargo-shuttle
      run: cargo install cargo-shuttle --locked

    - name: Deploy auth-gateway
      run: |
        cd services/auth-gateway
        shuttle deploy --allow-dirty
      env:
        SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}

    - name: Deploy projects
      run: |
        cd services/projects
        shuttle deploy --allow-dirty
      env:
        SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}

    - name: Deploy backlog
      run: |
        cd services/backlog
        shuttle deploy --allow-dirty
      env:
        SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}

    - name: Deploy readiness
      run: |
        cd services/readiness
        shuttle deploy --allow-dirty
      env:
        SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
