name: Deploy to Vercel

on:
  push:
    branches: [ main ]
    paths: [ 'apps/web/**' ]
  workflow_dispatch:

defaults:
  run:
    working-directory: apps/web

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build
        env:
          # Production environment variables
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          NEXT_PUBLIC_PROJECTS_API_URL: ${{ secrets.NEXT_PUBLIC_PROJECTS_API_URL }}
          NEXT_PUBLIC_BACKLOG_API_URL: ${{ secrets.NEXT_PUBLIC_BACKLOG_API_URL }}
          NEXT_PUBLIC_READINESS_API_URL: ${{ secrets.NEXT_PUBLIC_READINESS_API_URL }}
          NEXT_PUBLIC_PROMPT_BUILDER_API_URL: ${{ secrets.NEXT_PUBLIC_PROMPT_BUILDER_API_URL }}
          NEXT_PUBLIC_ENABLE_AI_FEATURES: ${{ secrets.NEXT_PUBLIC_ENABLE_AI_FEATURES }}
          NEXT_PUBLIC_ENABLE_MOCK_DATA: ${{ secrets.NEXT_PUBLIC_ENABLE_MOCK_DATA }}

      - name: Deploy to Vercel
        id: deploy
        uses: vercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: apps/web

      - name: Update deployment status
        if: always()
        run: |
          if [ "${{ steps.deploy.outcome }}" == "success" ]; then
            echo "✅ Frontend deployed successfully to Vercel"
            echo "🔗 URL: ${{ steps.deploy.outputs.url }}"
          else
            echo "❌ Frontend deployment failed"
            exit 1
          fi